### ISSUE TITLE
Allow for specifying colors via CSS rather than via props

### ISSUE THREAD

**Issue by Xapphire13** [kirillDanshin/halogenium#15]
Right now the colors are done via props. In order to add a color via CSS I need to render the loader like:
```JSX
<ScaleLoader className="halogenium-loader" />
```

And then add CSS like:
```less
.halogenium-loader {
  div {
    background-color: blue !important;
  }
}
```

Ideally, I wouldn't have to override all child `<div/>` elements using the `!important` rule, instead something like this would be enough:

```less
.halogenium-loader {
  color: blue;
}
```
